name: Index

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download script
        run: curl -o index.sh https://raw.githubusercontent.com/WizzardSK/gameflix/refs/heads/main/index.sh

      - name: Run script
        run: bash index.sh
