name: Generate Directory Listings

on:
  push:
    branches:
      - main

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gacts/directory-listing@v1
        with:
          target: ./assets
          ignore: |
            build/**
            **/index.html
            node_modules/**,**/*.log
          show-hidden: true
          overwrite: true
